version: '3.4'

services:
  vogcodechallenge.api:
    image: ${DOCKER_REGISTRY-}vogcodechallengeapi
    build:
      context: .
      dockerfile: VogCodeChallenge.API/Dockerfile
    depends_on:
        - database

  database:
    image: microsoft/mssql-server-linux:2017-CU3
    container_name: webapidb
    ports:
        - 1433:1433
    environment:
        ACCEPT_EULA: "Y"
        MSSQL_SA_PASSWORD: "<YourStrong!Passw0rd>"
